# Generated by Django 2.1.7 on 2019-02-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='note',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
