# Generated by Django 2.2.2 on 2019-08-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='file',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
        migrations.AddField(
            model_name='tag',
            name='imagename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
