# Generated by Django 2.1.7 on 2019-02-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20190224_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='note',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
