# Generated by Django 2.1.7 on 2019-02-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_auto_20190224_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='option_1',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='no1_recordings', to='birds.Bird'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='option_2',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='no2_recordings', to='birds.Bird'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recording',
            name='has_file',
            field=models.BooleanField(default=False),
        ),
    ]
