# Generated by Django 2.1.7 on 2019-02-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0005_auto_20190228_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='option_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no1_recordings', to='birds.Bird'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='option_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no2_recordings', to='birds.Bird'),
        ),
    ]
