# Generated by Django 2.1.7 on 2019-03-17 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0007_auto_20190303_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phase', models.IntegerField(blank=True, default=1)),
                ('file_type', models.CharField(choices=[('i', 'image'), ('a', 'audio'), ('v', 'video')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('file_on_server', models.BooleanField()),
                ('note', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('importance', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='birds.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(blank=True, choices=[(0, 'owner'), (1, 'expert'), (2, 'layman')], default=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='birds.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prior', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='birds.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='birds.Record')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='birds.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='bird',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='recording',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='option_2',
        ),
        migrations.DeleteModel(
            name='Bird',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='Recording',
        ),
        migrations.AddField(
            model_name='identification',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='birds.Record'),
        ),
        migrations.AddField(
            model_name='identification',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='birds.Tag'),
        ),
        migrations.AddField(
            model_name='identification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
