# Generated by Django 2.1.7 on 2019-03-19 13:40

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0008_auto_20190318_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='directory',
            field=models.CharField(default='default', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
            preserve_default=False,
        ),
    ]
