# Generated by Django 2.1.7 on 2019-03-21 17:19

import birds.validators
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0009_project_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='note',
        ),
        migrations.AlterField(
            model_name='project',
            name='directory',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), birds.validators.KeywordValidator(keyword_list=['admin', 'rest_api'])]),
        ),
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together={('record', 'tag')},
        ),
    ]
