# Generated by Django 2.1.7 on 2019-03-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0010_auto_20190321_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='birds'),
        ),
    ]
