# Generated by Django 2.1.7 on 2019-04-02 14:27

import birds.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0012_auto_20190321_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=birds.models.Record.record_files_path),
        ),
        migrations.AlterField(
            model_name='identification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=birds.models.Tag.tag_images_path),
        ),
        migrations.AlterUniqueTogether(
            name='right',
            unique_together={('user', 'project')},
        ),
    ]
