# Generated by Django 2.1.7 on 2019-04-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0013_auto_20190402_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='filename',
        ),
    ]
