# Generated by Django 2.1.7 on 2019-04-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0015_auto_20190403_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file_type',
            field=models.CharField(choices=[('i', 'image'), ('a', 'audio')], max_length=1),
        ),
    ]
