# Generated by Django 2.1.7 on 2019-04-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0017_auto_20190413_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='filename',
            field=models.CharField(default='x.mp3', max_length=50),
        ),
    ]
