# Generated by Django 2.1.7 on 2019-04-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0018_record_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='filename',
            field=models.CharField(max_length=50),
        ),
    ]
